name: Build Docker image

on:
  workflow_dispatch:
  
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Docker build
        run: |
          cd sample-packages/docker
          docker build .
