name: Publish package to package repository

env:
  USERNAME: gclhub-org
  IMAGE_NAME: gclapp
  IMAGE_VER: 0.0.1
  ACTIONS_STEP_DEBUG: true

on:
  release:
    types:
      - created
  workflow_dispatch:
      
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Docker build
        run: |
          cd sample-packages/docker
          ID=$(docker build -q -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VER }} .)
          echo "ID=$ID" >> $GITHUB_ENV

      - name: Publish Docker container to package repo
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ env.USERNAME }} --password-stdin
          docker tag ${{ env.ID }} ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VER }}
          docker push ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VER }}
          
